trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
# 1. Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'   # or 6.0.x depending on your project

# 2. Restore dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 3. Build project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

# 4. Publish project (creates zip package)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# 5. Deploy to Azure Function App (or Web App)
- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'AzureServiceConnectionName'   # 👈 service connection name
    appType: 'functionApp'                        # or 'webApp' if deploying Web App
    appName: 'ProcessEnrollment'                  # 👈 your Function/Web App name
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'